### ISSUE TITLE
Question - about migrate Java old system

### ISSUE THREAD

**Issue by hatung** [berkesa/moleculer-java#12]
Hello everyone,
I have old java client and I want integrate it into moleculer system by sending event and call action from moleculer services directly.
How can I do in this situation? Sorry I am newbee in Java and moleculer.

**Comment by berkesa** [comment]
Hello Hatung,

java-based and nodeJS-based Moleculer nodes can communicate through a Message Broker.
In the first step you will need an installed Message Broker (windows/linux) service,
like REDIS or NATS. Each Moleculer node (Java and NodeJS) will be connected to this service.

Molecular services mostly send JSON messages to each other.
JSON structures are handled by a java-based Moleculer with a "Tree" object:

```java
Tree json = new Tree();
json.put("name", "tom");
json.put("phone", "555-123-4567");
json.putList("emails").add("first@abc.com").add("second@abc.com");
```
This is similar to the DOM API as you build an XML.
The values in "Tree" can be easily accessed:

```java
String name = json.get("name", "default name");
String phone = json.get("phone", "default phone");
for (Tree email: json.get("emails")) {
  String mail = email.asString();
}
```
For more information about using "Tree", see the JavaDoc of Tree.
The next step in Your java project is to refer to all the required libraries
(as a Maven on Gradle dependency, or download the proper JARs directly).
You will need at least the following four dependency groups:

1.) Moleculer Core JARs:

```java
compile group: 'com.github.berkesa', name: 'moleculer-java', version: '1.0.8'
```
2.) Logger APIs (Moleculer uses SLF4j logger API):

```java
compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.25'
compile group: 'org.slf4j', name: 'slf4j-jdk14', version: '1.7.25'
compile group: 'org.slf4j', name: 'log4j-over-slf4j', version: '1.7.25'
compile group: 'org.slf4j', name: 'jcl-over-slf4j', version: '1.7.25'
```
3.) Sigar API (for access the CPU usage):

```java
compile (group: 'org.fusesource', name: 'sigar', version: '1.6.4') {
  exclude group: 'log4j', module: 'log4j'
}
```
4.) Dependency of the Transporter (eg. NATS or REDIS):

```java
REDIS: compile group: 'biz.paluch.redis', name: 'lettuce', version: '4.5.0.Final'
or
NATS: compile group: 'io.nats', name: 'jnats', version: '2.4.1'
```
After that, You can create a MessageBroker (this is the Moleculer's Java API):

```java
  ServiceBrokerConfig cfg = new ServiceBrokerConfig();
  cfg.setNodeID("node1");

  Transporter transporter = new RedisTransporter("192.168.51.100"); // Modify the IP address
  cfg.setTransporter(transporter);

  ServiceBroker broker = new ServiceBroker(cfg);
  broker.start();
  
  // This may be because we have not yet connected to the other node.
  // Wait until the connection is established... (timeout = 10 sec)
  broker.waitForServices("myservice").waitFor(10000);

  // SEND EVENT:
  Tree data = new Tree();
  data.put("name", "tom");
  broker.broadcast("myevent", data);

  // CALL ACTION (REMOTE OR LOCAL):
  broker.call("myservice.action", data).then(rsp -> {
    out.println(rsp.asString()); // Print response
  }).catchError(err -> {
    err.printStackTrace(out); // Print error
  });
```
Also there is a sample Java project here:
https://github.com/moleculer-java/moleculer-java-gradle-demo

This is a more serious Spring-based project.
If you have any other questions, feel free to ask.

**Comment by hatung** [comment]
Thank you, It works perfectly
