### ISSUE TITLE
How to dynamically add/remove listener group in Spring?

### ISSUE THREAD

**Issue by kkaushik90f** [berkesa/moleculer-java#17]
I have multiple instances of "producer" spring boot app. This puts messages on a queue to "consumer" spring boot app. Consumer app then replies with the result by broadcasting it, so all instances of producer receive it. I'm using moleculer with nats transporter to do this broadcasting.

I want only the instance of producer that started the transaction to receive the broadcast result. I think I can achieve it by adding each transaction id as a listener group.

So the producer will add the transaction id as a Group within a Service. Not sure how exactly to do this part. I tried `broker.getConfig().getEventbus().addListeners(..., ...);` but this doesn't take group parameter.

Once this is done, the consumer will be able to broadcast with something like `broker.broadcast("producer", params, Groups.of("txn-id-1"));`. And once the producer receives it, it can remove "txn-id-1" group from the listeners.

Can you please help with how can I add and remove groups like this for each transaction dynamically? Also, is this the correct usage of groups or is there something better?

**Comment by berkesa** [comment]
When an event listener registers in a Moleculer cluster, the **nodes of the cluster notify each other** of the changed topology (who is watching who). This involves extra communication and it takes a while for every node to be aware of the changes. The cluster is fast if its structure is rarely changed.

For this reason, you should choose another solution **where the cluster structure is not constantly changing**. For expample the response can be returned by the consumer to the producer based on the producer's nodeID. So the request goes through **broadcast events** and the response is returned to the "sender" via **action calls** (when the sender's nodeID is in the event's structure).

**Comment by kkaushik90f** [comment]
Thank you @berkesa, this solution is perfect.
And thanks a lot for this project!
