### ISSUE TITLE
getMeta() not working

### ISSUE THREAD

**Issue by kkaushik90f** [berkesa/moleculer-java#18]
I am using NATS transporter and sending data from one Java microservice to another.

```
Tree request = new Tree();
request.put("firstName", "A");
request.put("middleName", "B");
request.put("lastName", "C");
request.put("dateOfBirth", LocalDate.EPOCH.toString());
request.getMeta().put("requestId", UUID.randomUUID().toString()); //META!
serviceBroker.call("idv.verify", request);
```

At the receiving end, I have:
```
public Action verify = ctx -> {
    log.debug("Message bus request received: {}", ctx.params);
    log.debug("Meta: {}", ctx.params.getMeta());
    return null;
};
```
The first log statement prints the payload that was sent correctly.
But the second one prints an empty meta.
I debugged and found that meta is null in the `ctx.params` object:

![image](https://user-images.githubusercontent.com/38212890/63568564-f8c7aa80-c5b8-11e9-8979-12763f672959.png)

Can you please advise why is meta not being sent?

**Comment by berkesa** [comment]
Thank you for the feedback!
I made a test case and saw that this bug really exists. 
I'll fix it soon, and I'll let you know if I've uploaded the fixed version to the Maven server.

**Comment by berkesa** [comment]
Fixed in **Moleculer-Java** version **1.1.2**. I uploaded the changes under the Maven server. It will be available for download in about 10-20 minutes.

```xml
<dependencies>
	<dependency>
		<groupId>com.github.berkesa</groupId>
		<artifactId>moleculer-java</artifactId>
		<version>1.1.2</version>
		<scope>runtime</scope>
	</dependency>
</dependencies>
```
Please let me know if everything is ok or close the ticket. Thanks!

**Comment by kkaushik90f** [comment]
Thank you @berkesa for fixing it promptly, it works now!
Just a minor, unrelated question:
`broker.call(...)` returns a Promise from your datatree library. I prefer using JDK classes wherever possible, so I immediately call `.toCompletableFuture()` on this and work with this CompletableFuture instance (Java 11). Am I losing anything by not using Promise?

**Comment by berkesa** [comment]
Promise is not a competitor to CompletableFuture. Technically the Promise object is a thin layer at the top of a CompletableFuture object.

Promise is good if you want to use a **simpler API that is similar to JavaScript syntax**, but if you prefer CompletableFuture, use it. There is no significant difference in speed / performance between the two APIs (Promise and CompletableFuture). When an "action" returns a value, you can return the following object types:

1.) Promise

2.) CompletableFuture

3.) CompletionStage

4.) Throwable (-> Moleculer Error Strucure in JSON format)

5.) Tree (-> JSON structure)

6.) Map (HashMap, LinkedHashMap, etc -> Tree -> JSON structure)

7.) One simple variable (eg. string, number, boolean, date, uuid)

8.) null (mapped to JSON "null")

..so the returned value can be a CompletableFuture also!
It's important to be able to convert to JSON and not contain special/unknown object types.
