### ISSUE TITLE
NATS connection closed

### ISSUE THREAD

**Issue by molobala** [berkesa/moleculer-java#19]
Hello,

I'm having a trouble with NATS Transporter using Spring Boot
When I use Nats-Streaming I have no issue. But with Nats I'm getting  NATS connection closed.

My Transporter config if that can help

```java

@Bean
public static NatsTransporter transporter(){
	NatsTransporter transporter =  new NatsTransporter();
	transporter.setSerializer(new JsonSerializer());
	transporter.setConnectionTimeout(20000);
	transporter.setPingInterval(1500);
	transporter.setSecure(false);
	transporter.setUrls(new String[]{
		"10.172.1.109"
	});
	return transporter;
}

```

```
2020-02-12 09:01:50.008  INFO 93473 --- [ol-343-thread-1] s.moleculer.transporter.NatsTransporter  : NATS connection closed.
2020-02-12 09:01:50.008  INFO 93473 --- [ol-343-thread-1] s.moleculer.transporter.NatsTransporter  : Trying to reconnect...
2020-02-12 09:01:50.009  WARN 93473 --- [pool-1-thread-6] s.moleculer.transporter.NatsTransporter  : Unable to connect to NATS servers: nats://10.172.1.109:4222.
```

Thanks in advance.

**Comment by berkesa** [comment]
Hi!
Try setting the following to see more in the log:

transporter.setDebug(true);
transporter.setVerbose(true);

For me, the NAT tests run with "gnatsd.exe", version 1.3.0.
(anyway, do you have username-password authentication on the server?)

**Comment by molobala** [comment]
Hello,
I have my nats server running on a linux server.

A telnet on 10.172.1.109 4222 passes successfully
```
Trying 10.172.1.109...
Connected to s109.
Escape character is '^]'.
INFO {"server_id":"43sgTMRL217WqvYZpadJOs","version":"0.9.4","go":"go1.6.3","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
```
As you can see not auth is required on my nats server

I cant event connect directly to the NATS server using jnats lib as below

```java
 Options.Builder builder = new Options.Builder();
 builder.pingInterval(Duration.ofMillis(1500));
 builder.connectionTimeout(Duration.ofMillis(5000));

 builder.server("nats://10.172.1.109:4222");

 Options options = builder.build();
 Connection nc = null;
  try {
        nc = Nats.connect(options);
   } catch (IOException | InterruptedException e) {
        e.printStackTrace();
   }
   System.out.println("NATS pub-sub connection estabilished.");
   if(nc == null) {
      return;
   }
   System.out.println(nc.getStatus());
```

```
NATS pub-sub connection estabilished.
CONNECTED
```

**Comment by berkesa** [comment]
Interestingly, my code is almost identical to what you wrote:

https://github.com/moleculer-java/moleculer-java/blob/master/src/main/java/services/moleculer/transporter/NatsTransporter.java#L259

Based on this, I do not know what the problem may be.
I still suggest that you try this setting to see if there is more information in the log:

transporter.setDebug(true);
transporter.setVerbose(true);

**Comment by berkesa** [comment]
Probably the problem is "nats-streaming". The "normal" NATS protocol and the "nats-streaming" are _not the same_. This transporter is for "normal" NATS protocol, not for streaming.

Under Linux/Travis I use **gnatsd-v1.3.0-linux-amd64**.zip:
https://github.com/moleculer-java/moleculer-java/blob/master/.travis.yml#L17
...and all the tests run without fail.

**Comment by molobala** [comment]
Working with `gnatsd-v1.3.0-linux-amd64.zip` .

Thank you.
