### ISSUE TITLE
Dynamic service discovery

### ISSUE THREAD

**Issue by giang12** [berkesa/moleculer-java#25]
hi is there plan to support dynamic service discovery as ref implemented in js version?

Goal: is to able to connect java & js services using Etcd3/redis for discorvery and nats for req/res transporter
https://moleculer.services/docs/0.14/registry.html#etcd3

**Comment by berkesa** [comment]
I'm sorry, but I don't think I'll implement this service discovery method in the near future.
If you are running a cluster of many nodes, you may want to try the TCP transporter.
