### ISSUE TITLE
[TRACING] - Elastic APM integration

### ISSUE THREAD

**Issue by molobala** [berkesa/moleculer-java#26]
Hello everyone,

  I'm about to migrate a good part of one our applications on moleculer (Js and Java), since we rely a lot on elastic APM as monitoring tool, I would like to know if there is any chance to get it work with moleculer-java package. Looking at the documentation but didn't find anything about tracing like the JS version of moleculer. Am I missing something?

**Comment by berkesa** [comment]
Unfortunately, the "tracing" feature is not implemented in the java version, only the metrics.
