### ISSUE TITLE
Is there a Java version of moleculer-channels?

### ISSUE THREAD

**Issue by KaneOne** [berkesa/moleculer-java#27]
I hope the event can be made persistent. For Node.js, there are moleculer-channels middleware options available. I'm wondering if there are similar moleculer-channels for Java, or what approach should I take to achieve event persistence? Thank you.

**Comment by berkesa** [comment]
_> I'm wondering if there are similar molecular channels for Java._

No such feature is implemented in the java version.

It can only send events and call actions in the java version. In addition, several types of cache are implemented (local memory, Redis), various transporter implementations (NATS, Redis, MQTT, etc.), and call logics (round-robin, etc.), there is a circuit breaker for error handling. Metrics. There is a web and websocket extension for it. The java implementation can work together with the JS implementation on a basic level, but the JS version can do much more. Eg. tracing and event persistence.
